name: Build and Unit Test Successful

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.20.0
        uses: actions/setup-node@v2
        with:
          node-version: [16.20.0]
      - run: npm install
      - run: npm run build
      - run: npm run test
